services:
  microservice:
    build: 
      context: .
      dockerfile: microservice/Dockerfile
    volumes:
      - ./microservice:/app
    ports:
      - "9000:9000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/securesight
    ports:
      - "8000:8000"
    
  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app/securesight/frontend
    ports:
      - "80:80"

networks:
  default:
    driver: bridge