services:
  microservice:
    build: 
      context: .
      dockerfile: microservice/Dockerfile
    ports:
      - "9000:9000"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
      
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: >
      sh -c "
      python manage.py makemigrations authapi videoanalytics &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000 & 
      celery --app=securesight worker -l info"
      
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

networks:
  default:
    driver: bridge