services:
  microservice:
    build: 
      context: .
      dockerfile: microservice/Dockerfile
    ports:
      - "9000:9000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000 & 
      celery --app=securesight worker -l info"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"

networks:
  default:
    driver: bridge