# Generated by Django 5.0.2 on 2025-03-05 07:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mkv'])])),
                ('processed', models.BooleanField(default=False)),
                ('ai_processed', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='videos/thumbnails/')),
                ('slug', models.CharField(max_length=11, unique=True)),
                ('video_versions', models.JSONField(blank=True, default=dict)),
                ('log', models.JSONField(blank=True, default=dict)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
